### ISSUE TITLE
Plugin for JSON text sequences (RFC7464)

### ISSUE THREAD

**Issue by randomstuff** [turicas/rows#122]
It might be useful to have a plugin/option for JSON sequence, [RFC7464](https://tools.ietf.org/html/rfc7464), and as a extensions "one JSON object per line".

**Comment by turicas** [comment]
Isn't it the same as #202?

**Comment by randomstuff** [comment]
Yeeaah, it's kinda the same thing but it's not exactly the same thing.

In json-seq each line starts with an RF character. I'm not sure it should be readable as JSON lines because of this because a string containing RF is not a valid JSON string. Additionally, the added RF allows to silently drop erroneous lines from the json-seq stream.

**Comment by turicas** [comment]
@randomstuff given this, I'm going to close this issue and maintain #202 -- if jsonl is implemented, you can create a simple wrapper function to read a JSON text sequence, remove the RS and return it to the jsonl reader. This way we'll oficially support a good format and you can also easily implement a wrapper to support the other.
If you can provide this wrapper function we can add it to the examples folder. :)

**Comment by randomstuff** [comment]
ok :)
