### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by williamjmorenor** [turicas/rows#144]
Hi

We are working in:

https://fedoraproject.org/wiki/FAD_Python_3_Porting_2015

So I will try to help to improve the python3 support for rows, please note than rawhide has python3.5 and fedora 23 has python3.4

**Comment by turicas** [comment]
Hello, @williamjmorenor, thanks for your help!
We already have an issue to track Python 3 support on rows: #46. I'm closing this issue so we can continue there, ok?
