### ISSUE TITLE
UserWarning: Call to deprecated function or class get_active_sheet

### ISSUE THREAD

**Issue by kretcheu** [turicas/rows#145]
Hi, when I build package for Debian, debhelper tools runs pybuild, showing this warnings [1]
I use the lastest source: git20151115.837b41.

Is there something here or other has the same problem?
thanks.

[1] pybuild --test --test-nose -i python{version} -p 2.7 --dir .
I: pybuild base:184: cd /pkgs/pkg-rows/rows-0.1.1+git20151115.837b41/.pybuild/pythonX.Y_2.7/build; python2.7 -m nose tests
...................................................................................................../usr/lib/python2.7/dist-packages/openpyxl/workbook/workbook.py:102: UserWarning: Call to deprecated function or class get_active_sheet (Use the .active property).
  def get_active_sheet(self):
/usr/lib/python2.7/dist-packages/openpyxl/workbook/workbook.py:102: UserWarning: Call to deprecated function or class get_active_sheet (Use the .active property).
  def get_active_sheet(self):
./usr/lib/python2.7/dist-packages/openpyxl/workbook/workbook.py:102: UserWarning: Call to deprecated function or class get_active_sheet (Use the .active property).
  def get_active_sheet(self):
./usr/lib/python2.7/dist-packages/openpyxl/workbook/workbook.py:102: UserWarning: Call to deprecated function or class get_active_sheet (Use the .active property).
  def get_active_sheet(self):
..........................
----------------------------------------------------------------------
Ran 129 tests in 1.936s

OK

**Comment by turicas** [comment]
@kretcheu, I just fixed it! I was happening only on the new version of openpyxl (and I had an older version here). Thank you. :)

**Comment by AncoraImparo** [comment]
I downloaded today version 2.3.5 of openpyxl but the the same warning appears.

**Comment by turicas** [comment]
@AncoraImparo, could you please run `pip freeze` into your environment and paste there the result?

**Comment by akirahuntington** [comment]
I have the same warning with version 2.3.5. I would appreciate your fixing it. My environment is:
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.4.1
cssselect==0.9.1
decorator==4.0.9
et-xmlfile==1.0.1
ipython==4.2.0
ipython-genutils==0.1.0
jdcal==1.2
lxml==3.6.0
openpyxl==2.3.5
pickleshare==0.7.2
pyperclip==1.5.27
requests==2.10.0
selenium==2.53.2
Send2Trash==1.3.0
simplegeneric==0.8.1
traitlets==4.2.1

**Comment by turicas** [comment]
@akirahuntington probably you don't have the latest rows version: the current `develop` branch does not use `.get_active_sheet` (it uses `.active` instead) since Tue Nov 17 14:21:07 2015 (commit 94fd94b3ae0f8fea133da3a572cafb71841a851d).
