### ISSUE TITLE
xlsx character bug

### ISSUE THREAD

**Issue by lichti** [turicas/rows#179]
The ROWS command fail when one column has a percent character in the header line.

Command exemple:
rows query 'select * from table1 ' exemplo.xlsx

Reproduction with rows 0.2.0:
http://pastebin.com/CSyHj9uc

Reproduction with rows 0.3.0dev0:
http://pastebin.com/Q4Yf7CC2

Example file:
[exemplo.xlsx](https://github.com/turicas/rows/files/398691/exemplo.xlsx)

**Comment by turicas** [comment]
@lichti, thanks for reporting! The problem was in the `rows.utils.slug` function, which creates a "good name" for all field names (`'Query Occurrence"( % ),"First Seen'` to `'query_occurrence_first_seen'`, for example). It's already fixed on `develop` branch.
