### ISSUE TITLE
for branch python-3(rows support python3), get AttributeError: module 'types' has no attribute 'NoneType' when try to parse parquet file

### ISSUE THREAD

**Issue by redleaf2000** [turicas/rows#186]
I installed newest parquet 1.1 for python 3.5, and thrift 0.9.3,  and rows3 (python-3 support branch)
 and i try to debug my code like this:

import rows
table = rows.import_from_parquet('nation.parquet')
for row in table:
   print(row)  # access fields values with `rows.field_name`

get error as below:
   import rows
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
...
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Python35\lib\site-packages\rows-0.3.0.dev1-py3.5.egg\rows\fields.py", line 39, in <module>
  File "C:\Python35\lib\site-packages\rows-0.3.0.dev1-py3.5.egg\rows\fields.py", line 46, in Field
AttributeError: module 'types' has no attribute 'NoneType'

for fields.py, the code is like this:
class Field(object):
    """Base Field class - all fields should inherit from this

    As the fallback for all other field types are the BinaryField, this Field
    actually implements what is expected in the BinaryField
    """
    TYPE = (types.NoneType, )

**Comment by turicas** [comment]
@redleaf2000, I didn't finish the migration to support Python3, so sorry, I can't help you -- you need to wait for the work to be finished.
