### ISSUE TITLE
fields.DecimalField does not handle decimal separators other than '.'

### ISSUE THREAD

**Issue by draug3n** [turicas/rows#215]
I have CSV data from a Danish bank. Using the locale-aware settings, i get numbers in the form '1.234,56' imported as fields.FloatField -> '1234.56'. If I try and force the type to be fields.DecimalField, it errors out.

A quick scan of the code indicates a hard-coded '.' decimal separator. The da_DK locale (and others) also use a '.' for a thousands separator, which probably should be accounted for as well.

**Comment by turicas** [comment]
Hello!

I've compiled the `da_DK` locale here and tried the following code:

```python
>>> import rows
>>> with rows.locale_context('da_DK.UTF-8'):
...     print(rows.fields.DecimalField.deserialize('1.234,56'))
... 
1234.56
```

It worked as expected!
Could you please share the code and data you found the problem?

Note: the decimal place hardcoded is inside `rows.fields.DecimalField.serialize`: the serialization of a `Decimal` object will **always** have a `.` as a decimal separator, so there's no problem with this part of the code.

**Comment by draug3n** [comment]
I concede I may have misread the '.' in the code - happy hacker amateur here :)

I'm parsing my bank statements, with numbers such as `-237,08' and `6.000.00`, in a specific column. It gets auto-imported as a float field, but passing the OrderedDict of fieldnames in, and specifiying as DecimalField errors out, "this cannot be a DecimalField". Setting it to be a float works.

I just did some testing, and the serialize string stripped the `-` from `-1.234,56`. Preserving the sign is rather important to my use-case. No errors, though. The numbers stay negative as floats.

Will report later after I get a chance to test with a real data file as input.

**Comment by draug3n** [comment]
just ran the HTML importer, with the relevant field specified to be Decimal. The first number in the column is `-613,34`, and the importer errors out with `.extract() raised an unexpected error: Can't be DecimalField`

table row in question:
`<tr class="odd"><td headers="colPosteringDato" class="date">10.02.2017</td><td headers="colIkonAdvis" class="icon"><a href="/kontooplysninger/servlet/PosteringsAdvisering?_BIGPopup=true&amp;_BigPopup=true&amp;_kontonr=efeqsfFp8KF3aROH-b__&amp;_posteringsident=nApWNgsfi4CmSfJHV5BbaJCckljrMwiHCaNX2J__&amp;_adviseringsident=nApWNgsfi4CmSfJHV5BbaJCckljrMwiHCaNX2J__" title="Meddelelse" class="serverpopup"><img src="/grafik/ikon_advis.gif" alt="Meddelelse" /></a></td><td headers="colPosteringTekst"><a href="/kontooplysninger/servlet/PosteringsAdvisering?_BIGPopup=true&amp;_BigPopup=true&amp;_kontonr=efeqsfFp8KF3aROH-b__&amp;_posteringsident=nApWNgsfi4CmSfJHV5BbaJCckljrMwiHCaNX2J__&amp;_adviseringsident=nApWNgsfi4CmSfJHV5BbaJCckljrMwiHCaNX2J__" title="Vis adviseringstekst" class="serverpopup">Food  </a></td><td headers="colPosteringRenteDato" class="date">10.02.2017</td><td headers="colPosteringBeloeb" class="amount negative">-613,95</td><td headers="colPosteringSaldo" class="amount">2.858,19</td><td headers="colAfstemt" class="icon"><img id="img0" src="/grafik/afstem_inaktiv.gif" alt="Du kan afstemme posteringen ved at klikke her" onclick="big.action.ajax.updateImage('UpdateImage','/overblik/servlet/Posteringer','Click','Image','afstemPostering','img0','lAfstem=img0','posteringsid=2017-02-10-04.32.47.649682&kontonr=_EucCgS*JX6iPTb6xKk3_','POST',false);" /></td></tr>`

**Comment by turicas** [comment]
@draug3n thanks for reporting this issue! I've fixed it and released [a bugfix version on PyPI](https://pypi.python.org/pypi/rows/0.3.1).
