### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by turicas** [turicas/rows#243]
May change license to LGPL.

**Comment by izabelacborges** [comment]
Can I do this?

Some files don't have the boilerplate for GNU 3.0 license. Those are inside the `examples/library` folder: 
* airports.py 
* brazilian_cities_wikipedia.py
* custom_field.py
* ecuador_radiodifusoras.py
* extract_links.py
* organizaciones.py
* slip_opinions.py
* usa_legislators.py
* uwsgi_log_plugin.py

I should put the boilerplate for the LGPL on those too, or keep it only for the files that already had the GPL license boilerplate?

**Comment by turicas** [comment]
@izabelacborges yes you can! For the examples I think it's better to release them as public domain, since you can use the code inside your application - so the LGPL license should only apply to library files (not for the examples, not for the docs).

Note: don't forget to add yourself as a contributor to `AUTHORS.md`. ;)
