### ISSUE TITLE
unsupported locale setting: Not sure if rows issue, or system issue

### ISSUE THREAD

**Issue by cuducos** [turicas/rows#260]
This report is based on an application running in a `python:3.6.1` Docker image container ,i.e. a Debian based system.

The app and the `ipython` mentioned use the same interpreter and are executed inside this container. The Brazilian locale was generated basically with:

```Dockerfile
RUN apt-get update \
    && apt-get install -y --no-install-recommends libmagic1 locales \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
```

---

Building this container and running `ipython` within it works nicely:

```python
In [1]: import locale

In [2]: locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
Out[2]: 'pt_BR.UTF-8'
```

However if I use [`rows` context manager](https://github.com/turicas/rows/blob/develop/rows/localization.py#L28-L47) it fails:

```
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/rows/localization.py", line 32, in locale_context
    locale.setlocale(category, old_name)
  File "/usr/local/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

I used `ipdb` and checked the arguments `rows` passes to `setlocale` and they match what I just tried in the console:

* `6` which is equal to `locale.LC_ALL`
* and the string `'pt_BR.UTF-8'`

Any ideas about how to start do debug this issue?

**Comment by cuducos** [comment]
Ok… just recreated the scenario with two files:

---

**Dockerfile**

```Dockerfile
FROM python:3.6.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends libmagic1 locales \
    && rm -rf /var/lib/apt/lists/*

# generate pt_BR locale
RUN sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && locale-gen

RUN pip install rows
COPY rows-locale.py rows-locale.py

CMD ["python", "rows-locale.py"]
```

---

**rows-locale.py**

```python
from decimal import Decimal

import rows


with rows.locale_context('pt_BR.UTF-8'):
    assert Decimal('3.1415') == rows.fields.DecimalField.deserialize('3,1415')
```

---

First build the container with `$ docker build -t rows_locale .`.

Now try to run the script with `$ docker run rows_locale`.

Here I get the following output:

```
Traceback (most recent call last):
  File "rows-locale.py", line 7, in <module>
    assert Decimal('3.1415') == rows.fields.DecimalField.deserialize('3,1415')
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/rows/localization.py", line 30, in locale_context
    locale.setlocale(category, old_name)
  File "/usr/local/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Finally try it out with the console and check it works:

```console
docker run -it --rm rows_locale python
Python 3.6.1 (default, Jul  8 2017, 05:00:20)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
'pt_BR.UTF-8'
```

**Comment by cuducos** [comment]
Ok… we have an fix! @jonatasoli noticed that in the system the locale was `C.UTF-8` and suggested my to set `en_US.UTF-8` as the system default, which I did:

```diff
FROM python:3.6.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends libmagic1 locales \
    && rm -rf /var/lib/apt/lists/*
- RUN sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
+ RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
+   && sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen \
+   && locale-gen

RUN pip install rows
COPY rows-locale.py rows-locale.py

CMD ["python", "rows-locale.py"]
```

This proved successful.

@turicas is this issue useful for `rows` community? Should I close it?

**Comment by turicas** [comment]
@cuducos What `rows.locale_context` does is:

- Get the current locale, store it as `old_name`;
- When entering the context manager: change to the locale to the one you want;
- When exiting the context manager: change to the old locale.

In the first `Dockerfile` you didn't build the `en_US.UTF-8` locale but `locale.getlocale()` returns `('en_US', 'UTF-8')` and rows store it (you can add `import locale; print(locale.getlocale())` to your code and see). I don't know why exactly `locale` has this behavior, but it does not seem to be a `rows` bug.

BTW I think we can use this issue to have a better documentation about locale (like: warning the user to build the locale for her system etc.). Would you like to do this enhancement?

**Comment by cuducos** [comment]
Thanks for the explanation : )

> BTW I think we can use this issue to have a better documentation about locale (like: warning the user to build the locale for her system etc.). Would you like to do this enhancement?

Great! I [suggested a couple of lines](https://github.com/turicas/rows/pull/269), I think we might close this issue and focus on the proper documentation there, right?
