### ISSUE TITLE
Convert or print TSE html page

### ISSUE THREAD

**Issue by josircg** [turicas/rows#289]
Python 2.7.6
Rows 0.3.1

rows print 'http://www.tse.jus.br/eleicoes/eleicoes-2018/divulgacandcontas#/partidos/2018/2022802018/BR/2'

Erro:
  File "/var/webapp/django-rows/local/lib/python2.7/site-packages/rows/plugins/plugin_html.py", line 70, in import_from_html
    table = tables[index]
IndexError: list index out of range

**Comment by turicas** [comment]
This page does not have a `<table>` directly in the HTML - the table created there is loaded by JavaScript. `rows` does not support running a webpage like a browser (executing JS, for example), so the behavior you expect is not on the library features -- it's more on Web scraping area than in the parsing/converting documents.
If you can use Selenium to open a browser and get the modified HTML (after JS executed and loaded data), you can then use this HTML to be parsed by `rows`.
