### ISSUE TITLE
Integer field detected for numbers started with zero

### ISSUE THREAD

**Issue by bruno-santiago** [turicas/rows#302]
Rows is identifying a column as integer when the data on a column is a number that starts with zero.

When a number starts with zero, that number is more likely to be an registration number than an amount.

Let's supose that we are dealing with Brazilian CPF. 
If a cell contains a CPF started with zero, that would lead to data loss.

09340192213 would be converted to 9340192213

**Comment by anapaulagomes** [comment]
I'm facing the same issue with rows 0.4.1.

I have the string `00798360000180` and it's turning it into `798360000180`.

**Comment by anapaulagomes** [comment]
Never mind! :)
