### ISSUE TITLE
Converter PDF x TXT

### ISSUE THREAD

**Issue by Danielydsm** [turicas/rows#309]
Bom dia, estou tentando converter um arquivo pdf escaneado para texto (o pdf contém tabelas).
Consegui instalar a biblioteca rows e as dependências rows[pdf], rows[cli]. Quando eu tento rodar o código em prompt command: rows pdf-to-text teste.pdf result.txt
Eu tenho o seguinte erro:
![image](https://user-images.githubusercontent.com/38949002/53242972-245aee00-3685-11e9-88d4-2e8b6901cca7.png)

Alguma ideia do que possa ser o problema?

**Comment by turicas** [comment]
Oi, @Danielydsm. Parece um problema com uma das dependências opcionais da rows, a biblioteca [file-magic](https://pypi.org/project/file-magic/).

Você poderia, por favor, alterar o arquivo `C:\Program Files\Python36\lib\site-packages\rows\utils.py` e testar novamente? Se funcionar eu já subo a alteração na próxima versão. Procure pelas linhas:

```python
 try:
    import magic  # TODO: check if it's from file-magic library
except ImportError:
     magic = None
```

e substitua-as por:

```python
try:
    import magic
except (ImportError, TypeError):
    magic = None
```

**Comment by Danielydsm** [comment]
Boa tarde, eu tentei executar novamente o código antes de mudar as linhas acima e ele funcionou normal =S 

Muito obrigada.

**Comment by turicas** [comment]
@Danielydsm você fez alguma instalação/desinstalação de pacotes Python no virtualenv (ou no sistema)? Me parece que o problema está relacionado com a biblioteca file-magic ou com a python-magic, então qualquer instalação/desinstalação que altere a versão desses pacotes pode ter alterado o comportamento.

**Comment by Danielydsm** [comment]
Eu desinstalei o wand (acredito que esta biblioteca também tenha o magic). 

Bom executei o comando: rows pdf-to-text test.pdf resultado.txt 
Ele roda sem erros, mas cria um txt em branco. 

(Estou tentando extrair textos de um pdf escaneado)

**Comment by turicas** [comment]
@Danielydsm me parece que a [wand não depende de nenhuma dessas bibliotecas](https://github.com/emcconville/wand/blob/master/setup.py), então pode ter sido alguma outra alteração no virtualenv ou no sistema operacional (o erro que aconteceu contigo parece ser pela falta da libmagic instalada no sistema, então algum outro softrware pode tê-la instalado).

Sobre o PDF/TXT: a versão atual não faz OCR, então só vai retornar a parte de texto do PDF.

**Comment by Danielydsm** [comment]
Entendi, poxa então não serve para o projeto que estou tentando implementar. Preciso extrair textos de PDFs escaneados. 

Eu estou usando o Win server 2012 numa VM, e até onde eu me lembre só reiniciei a maquina e desinstalei o wand. Fora isso, nesta maquina tenho o Imagemagick (7.0.8-Q16-HDRI) mas não fiz nenhuma alteração com ele. 

Muito obrigada pelo suporte.
