### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by marcelo-pereira-pcst** [turicas/rows#331]
Bom dia!

Estou aprendendo Python, então este pode ser um erro bem simples de resolver, mesmo assim não faço ideia do que pode ser feito:

Ao tentar importar o rows aparece a mensagem do título.

**Comment by turicas** [comment]
Oi, @tbmpereira. Já existe uma issue para essa quesão, dê uma olhada: https://github.com/turicas/rows/issues/306

**Comment by marcelo-pereira-pcst** [comment]
Olá Álvaro.

Obrigado pela resposta mas meu problema persiste. Agora há um erro de
atributo


  File
"C:\Users\mapereira\AppData\Local\Continuum\anaconda3\lib\site-packages\rows\plugins\sqlite.py",
line 26, in <module>
    import rows.fields as fields

AttributeError: module 'rows' has no attribute 'fields'

Marcelo

Em ter, 10 de set de 2019 às 11:31, Álvaro Justen <notifications@github.com>
escreveu:

**Comment by turicas** [comment]
Responda na outra issue, por favor.

**Comment by marcelo-pereira-pcst** [comment]
sim, eu respondi primeiro lá

**Comment by marcelo-pereira-pcst** [comment]
https://github.com/turicas/rows/issues/306#issuecomment-530000098
