### ISSUE TITLE
Create a website

### ISSUE THREAD

**Issue by turicas** [turicas/rows#43]
Should have:
- General information
- Links to GitHub (code, issues etc.)
- Installation instructions (using `pip`, `setup.py` and `apt-get`)
- Documentation (may use the [continuous docs](https://github.com/icgood/continuous-docs/) approach)

**Comment by turicas** [comment]
@raphapassini, you may be interested in contributing with this issue. ;-) I'd start with docstrings.

**Comment by raphapassini** [comment]
Yeap! I'll plug sphinx this weekend. :)
