### ISSUE TITLE
Necessary dependencies

### ISSUE THREAD

**Issue by cassiobotaro** [turicas/rows#91]
When I run the tests locally[branch develop], I caught two errors. 
We have two missing dependencies, xlrd and lxml. 
lxml can be a headache because it has system dependencies. How to proceed? Only add to requirements?

**Comment by turicas** [comment]
You can see on [Installation](https://github.com/turicas/rows#installation) section the procedures to install optional dependencies for plugins, like:

```bash
pip install rows[xls]  # will install `xlrd` and `xlwt`
pip install rows[html]  # will install `lxml`
pip install rows[all]  # will install *all* optional dependencies
```

You can also check the [Developing](https://github.com/turicas/rows#developing) sections where I suggest you to create a virtualenv, install the package with `--editable` inside the virtualenv and then install all development requirements. To summarize:

```bash
mkvirtualenv rows
pip install --editable .[all]
pip install -r requirements-development.txt
# now you can run `make test` gracefully
```
